/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MediaRouteImport } from './routes/media'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as HeritageIndexRouteImport } from './routes/heritage.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as StoriesDetailsRouteImport } from './routes/stories.details'
import { Route as OrganizationsDetailsRouteImport } from './routes/organizations.details'
import { Route as HeritageUpcomingRouteImport } from './routes/heritage.upcoming'
import { Route as HeritageDetailsRouteImport } from './routes/heritage.details'
import { Route as EventsDetailsRouteImport } from './routes/events.details'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ArtistsPortfolioRouteImport } from './routes/artists.portfolio'
import { Route as AccountWishlistGeneralRouteImport } from './routes/account.wishlist-general'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountBiddingRouteImport } from './routes/account.bidding'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageIndexRoute = HeritageIndexRouteImport.update({
  id: '/heritage/',
  path: '/heritage/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesDetailsRoute = StoriesDetailsRouteImport.update({
  id: '/stories/details',
  path: '/stories/details',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsDetailsRoute = OrganizationsDetailsRouteImport.update({
  id: '/organizations/details',
  path: '/organizations/details',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageUpcomingRoute = HeritageUpcomingRouteImport.update({
  id: '/heritage/upcoming',
  path: '/heritage/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageDetailsRoute = HeritageDetailsRouteImport.update({
  id: '/heritage/details',
  path: '/heritage/details',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsDetailsRoute = EventsDetailsRouteImport.update({
  id: '/events/details',
  path: '/events/details',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsPortfolioRoute = ArtistsPortfolioRouteImport.update({
  id: '/artists/portfolio',
  path: '/artists/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistGeneralRoute = AccountWishlistGeneralRouteImport.update({
  id: '/account/wishlist-general',
  path: '/account/wishlist-general',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/account/wishlist',
  path: '/account/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBiddingRoute = AccountBiddingRouteImport.update({
  id: '/account/bidding',
  path: '/account/bidding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/bidding': typeof AccountBiddingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/account/wishlist-general': typeof AccountWishlistGeneralRoute
  '/artists/portfolio': typeof ArtistsPortfolioRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/events/details': typeof EventsDetailsRoute
  '/heritage/details': typeof HeritageDetailsRoute
  '/heritage/upcoming': typeof HeritageUpcomingRoute
  '/organizations/details': typeof OrganizationsDetailsRoute
  '/stories/details': typeof StoriesDetailsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/heritage/': typeof HeritageIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/bidding': typeof AccountBiddingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/account/wishlist-general': typeof AccountWishlistGeneralRoute
  '/artists/portfolio': typeof ArtistsPortfolioRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/events/details': typeof EventsDetailsRoute
  '/heritage/details': typeof HeritageDetailsRoute
  '/heritage/upcoming': typeof HeritageUpcomingRoute
  '/organizations/details': typeof OrganizationsDetailsRoute
  '/stories/details': typeof StoriesDetailsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/events': typeof EventsIndexRoute
  '/heritage': typeof HeritageIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/bidding': typeof AccountBiddingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/account/wishlist-general': typeof AccountWishlistGeneralRoute
  '/artists/portfolio': typeof ArtistsPortfolioRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/events/details': typeof EventsDetailsRoute
  '/heritage/details': typeof HeritageDetailsRoute
  '/heritage/upcoming': typeof HeritageUpcomingRoute
  '/organizations/details': typeof OrganizationsDetailsRoute
  '/stories/details': typeof StoriesDetailsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/heritage/': typeof HeritageIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/certificate'
    | '/contact'
    | '/faq'
    | '/media'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/wishlist'
    | '/account/bidding'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/account/wishlist-general'
    | '/artists/portfolio'
    | '/collections/$slug'
    | '/events/details'
    | '/heritage/details'
    | '/heritage/upcoming'
    | '/organizations/details'
    | '/stories/details'
    | '/account/'
    | '/admin/'
    | '/artists/'
    | '/events/'
    | '/heritage/'
    | '/organizations/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/certificate'
    | '/contact'
    | '/faq'
    | '/media'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/wishlist'
    | '/account/bidding'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/account/wishlist-general'
    | '/artists/portfolio'
    | '/collections/$slug'
    | '/events/details'
    | '/heritage/details'
    | '/heritage/upcoming'
    | '/organizations/details'
    | '/stories/details'
    | '/account'
    | '/admin'
    | '/artists'
    | '/events'
    | '/heritage'
    | '/organizations'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/certificate'
    | '/contact'
    | '/faq'
    | '/media'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/wishlist'
    | '/account/bidding'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/account/wishlist-general'
    | '/artists/portfolio'
    | '/collections/$slug'
    | '/events/details'
    | '/heritage/details'
    | '/heritage/upcoming'
    | '/organizations/details'
    | '/stories/details'
    | '/account/'
    | '/admin/'
    | '/artists/'
    | '/events/'
    | '/heritage/'
    | '/organizations/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  CertificateRoute: typeof CertificateRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MediaRoute: typeof MediaRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  AccountBiddingRoute: typeof AccountBiddingRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountWishlistGeneralRoute: typeof AccountWishlistGeneralRoute
  ArtistsPortfolioRoute: typeof ArtistsPortfolioRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  EventsDetailsRoute: typeof EventsDetailsRoute
  HeritageDetailsRoute: typeof HeritageDetailsRoute
  HeritageUpcomingRoute: typeof HeritageUpcomingRoute
  OrganizationsDetailsRoute: typeof OrganizationsDetailsRoute
  StoriesDetailsRoute: typeof StoriesDetailsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  HeritageIndexRoute: typeof HeritageIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage/': {
      id: '/heritage/'
      path: '/heritage'
      fullPath: '/heritage/'
      preLoaderRoute: typeof HeritageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/details': {
      id: '/stories/details'
      path: '/stories/details'
      fullPath: '/stories/details'
      preLoaderRoute: typeof StoriesDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/details': {
      id: '/organizations/details'
      path: '/organizations/details'
      fullPath: '/organizations/details'
      preLoaderRoute: typeof OrganizationsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage/upcoming': {
      id: '/heritage/upcoming'
      path: '/heritage/upcoming'
      fullPath: '/heritage/upcoming'
      preLoaderRoute: typeof HeritageUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage/details': {
      id: '/heritage/details'
      path: '/heritage/details'
      fullPath: '/heritage/details'
      preLoaderRoute: typeof HeritageDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/details': {
      id: '/events/details'
      path: '/events/details'
      fullPath: '/events/details'
      preLoaderRoute: typeof EventsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/portfolio': {
      id: '/artists/portfolio'
      path: '/artists/portfolio'
      fullPath: '/artists/portfolio'
      preLoaderRoute: typeof ArtistsPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist-general': {
      id: '/account/wishlist-general'
      path: '/account/wishlist-general'
      fullPath: '/account/wishlist-general'
      preLoaderRoute: typeof AccountWishlistGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/account/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/bidding': {
      id: '/account/bidding'
      path: '/account/bidding'
      fullPath: '/account/bidding'
      preLoaderRoute: typeof AccountBiddingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  CertificateRoute: CertificateRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MediaRoute: MediaRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  AccountBiddingRoute: AccountBiddingRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountWishlistGeneralRoute: AccountWishlistGeneralRoute,
  ArtistsPortfolioRoute: ArtistsPortfolioRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  EventsDetailsRoute: EventsDetailsRoute,
  HeritageDetailsRoute: HeritageDetailsRoute,
  HeritageUpcomingRoute: HeritageUpcomingRoute,
  OrganizationsDetailsRoute: OrganizationsDetailsRoute,
  StoriesDetailsRoute: StoriesDetailsRoute,
  AccountIndexRoute: AccountIndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  HeritageIndexRoute: HeritageIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
